export const OnramperCoverage = [
  {
    country: "Austria",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Belgium",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Denmark",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Estonia",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Finland",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Cyprus",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "France",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Switzerland",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Germany",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Hungary",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Poland",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Greece",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Ireland",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Italy",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Latvia",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Lithuania",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Luxembourg",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Malta",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Netherlands",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Portugal",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Slovakia",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Slovenia",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Spain",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Sweden",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Andorra",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "French Guiana",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Guadeloupe",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Martinique",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Mayotte",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Montenegro",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Réunion",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Saint Barthélemy",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Saint Martin",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Saint Pierre and Miquelon",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Åland",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Vatican City",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Croatia",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "American Samoa",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Samoa",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "United Kingdom",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "UK Faster Payments",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "India",
    payment_methods: ["IMPS", "UPI"],
    providers: ["transak", "wert"],
  },
  {
    country: "United States",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Puerto Rico",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "U.S. Virgin Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Guam",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Turks and Caicos Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Northern Mariana Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Norway",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Svalbard and Jan Mayen",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Faroe Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Greenland",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "New Zealand",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Cook Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Niue",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Pitcairn Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Tokelau",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Mexico",
    payment_methods: [
      "Card Payment",
      "AstroPay",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "MX_CASH",
      "SPEI_WL",
      "SPEI",
    ],
    providers: ["transak", "moonpay", "wert", "unlimit"],
  },
  {
    country: "Canada",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Australia",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Christmas Island",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Cocos [Keeling] Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Heard Island and McDonald Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Kiribati",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Nauru",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Norfolk Island",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Tuvalu",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Argentina",
    payment_methods: ["Card Payment", "AstroPay", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Brazil",
    payment_methods: [
      "AstroPay",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Pix Instant Payment",
      "PICPAY",
    ],
    providers: ["transak", "moonpay", "wert", "unlimit"],
  },
  {
    country: "Chile",
    payment_methods: ["AstroPay", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Costa Rica",
    payment_methods: ["Card Payment", "Apple Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Dominican Republic",
    payment_methods: [
      "Card Payment",
      "Google Pay",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Indonesia",
    payment_methods: [
      "Card Payment",
      "Google Pay",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Israel",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Japan",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "South Korea",
    payment_methods: ["Card Payment", "Apple Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Malaysia",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Paraguay",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Peru",
    payment_methods: [
      "Card Payment",
      "AstroPay",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Philippines",
    payment_methods: [
      "GCash",
      "Maya",
      "BPI",
      "Union Bank",
      "GrabPay",
      "ShopeePay",
      "Card Payment",
      "Google Pay",
    ],
    providers: ["transak", "wert"],
  },
  {
    country: "Singapore",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Fiji",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Kenya",
    payment_methods: [
      "Card Payment",
      "Google Pay",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Moldova",
    payment_methods: ["Card Payment", "Apple Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Bermuda",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Falkland Islands",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Czechia",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Iceland",
    payment_methods: ["Card Payment", "Apple Pay"],
    providers: ["transak"],
  },
  {
    country: "Romania",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Angola",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Belize",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Brunei",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Comoros",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Djibouti",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Dominica",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Grenada",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Saint Kitts and Nevis",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Saint Lucia",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Saint Vincent and the Grenadines",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Georgia",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Guatemala",
    payment_methods: ["Card Payment", "Apple Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Honduras",
    payment_methods: ["Card Payment", "Apple Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Hong Kong",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Kazakhstan",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Kyrgyzstan",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Madagascar",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Malawi",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Mauritania",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Oman",
    payment_methods: [
      "Card Payment",
      "Google Pay",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Papua New Guinea",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Rwanda",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "São Tomé and Príncipe",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Seychelles",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Solomon Islands",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Suriname",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Swaziland",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Tajikistan",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Tonga",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Turkmenistan",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Uruguay",
    payment_methods: ["Card Payment", "AstroPay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Colombia",
    payment_methods: [
      "PSE",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert", "unlimit"],
  },
  {
    country: "Taiwan",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Ghana",
    payment_methods: ["Card Payment"],
    providers: ["transak"],
  },
  {
    country: "United Arab Emirates",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Cambodia",
    payment_methods: ["Card Payment"],
    providers: ["transak"],
  },
  {
    country: "Serbia",
    payment_methods: ["Card Payment", "Apple Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Bahrain",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Macedonia",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Kuwait",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Armenia",
    payment_methods: ["Card Payment", "Apple Pay"],
    providers: ["transak"],
  },
  {
    country: "Curacao",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Aruba",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Azerbaijan",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak"],
  },
  {
    country: "Bahamas",
    payment_methods: ["Card Payment"],
    providers: ["transak"],
  },
  {
    country: "Cayman Islands",
    payment_methods: ["Card Payment"],
    providers: ["transak"],
  },
  {
    country: "Cape Verde",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Bosnia and Herzegovina",
    payment_methods: ["Card Payment"],
    providers: ["transak"],
  },
  {
    country: "Palestine",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Trinidad and Tobago",
    payment_methods: ["Card Payment"],
    providers: ["transak"],
  },
  {
    country: "Panama",
    payment_methods: ["Card Payment", "Apple Pay", "Google Pay"],
    providers: ["transak"],
  },
  {
    country: "Algeria",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak"],
  },
  {
    country: "Antigua and Barbuda",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Benin",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Bhutan",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Bulgaria",
    payment_methods: [],
    providers: ["moonpay", "wert"],
  },
  {
    country: "Burundi",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Cameroon",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Central African Republic",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Chad",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Republic of the Congo",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Egypt",
    payment_methods: [
      "Card Payment",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
      "Google Pay",
    ],
    providers: ["moonpay"],
  },
  {
    country: "El Salvador",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Equatorial Guinea",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Eritrea",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Gabon",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Gambia",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Guinea",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Jordan",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Moonpay Balance",
      "Paypal",
      "Google Pay",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Lesotho",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Liechtenstein",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Maldives",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Mali",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Marshall Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Micronesia",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Monaco",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Mozambique",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Namibia",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Niger",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Palau",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "San Marino",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Saudi Arabia",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Sierra Leone",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "South Africa",
    payment_methods: [
      "Card Payment",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
      "Google Pay",
    ],
    providers: ["moonpay", "wert"],
  },
  {
    country: "Sri Lanka",
    payment_methods: [
      "Card Payment",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
      "Google Pay",
    ],
    providers: ["moonpay", "wert"],
  },
  {
    country: "Tanzania",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Thailand",
    payment_methods: [
      "Card Payment",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
      "Google Pay",
    ],
    providers: ["moonpay", "wert"],
  },
  {
    country: "East Timor",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Togo",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Turkey",
    payment_methods: [
      "Card Payment",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
      "Google Pay",
    ],
    providers: ["moonpay", "wert"],
  },
  {
    country: "Uzbekistan",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Vietnam",
    payment_methods: [
      "Card Payment",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
      "Google Pay",
      "PAYME",
      "vietqr",
    ],
    providers: ["moonpay", "wert", "unlimit"],
  },
  {
    country: "Zambia",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Anguilla",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Bangladesh",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Bonaire",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "British Indian Ocean Territory",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "British Virgin Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Ivory Coast",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "French Polynesia",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Guernsey",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "UK Faster Payments",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Isle of Man",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "UK Faster Payments",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Jersey",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "UK Faster Payments",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Kosovo",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Liberia",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Macao",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Morocco",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "New Caledonia",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Saint Helena",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Sint Maarten",
    payment_methods: ["Card Payment"],
    providers: ["transak", "wert"],
  },
  {
    country: "Wallis and Futuna",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Botswana",
    payment_methods: [],
    providers: [],
  },
  {
    country: "Bouvet Island",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "Ecuador",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "French Southern Territories",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "Pix Instant Payment",
      "Bank Transfer",
      "ALIPAYPLUS",
      "SEPATRANSFER",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
  {
    country: "Guinea-Bissau",
    payment_methods: [],
    providers: ["wert"],
  },
  {
    country: "Montserrat",
    payment_methods: ["Card Payment", "Google Pay"],
    providers: ["transak", "wert"],
  },
  {
    country: "Nigeria",
    payment_methods: [
      "Card Payment",
      "Moonpay Balance",
      "Apple Pay",
      "Paypal",
      "Google Pay",
    ],
    providers: ["moonpay"],
  },
  {
    country: "South Georgia and the South Sandwich Islands",
    payment_methods: [
      "Manual Bank Transfer",
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Moonpay Balance",
      "Paypal",
      "UK Faster Payments",
    ],
    providers: ["transak", "moonpay", "wert"],
  },
  {
    country: "U.S. Minor Outlying Islands",
    payment_methods: [
      "Card Payment",
      "Apple Pay",
      "Google Pay",
      "Paypal",
      "UK Faster Payments",
      "Venmo",
      "ALIPAYPLUS",
    ],
    providers: ["transak", "moonpay", "stripe", "wert", "unlimit"],
  },
];
