export interface ICountryData {
  name: string;
  code: string;
  dial_code: string;
  flag: string;
  currency_name: string;
  currency_symbol: string;
}

export const COUNTRY_DATA: ICountryData[] = [
  {
    name: "Afghanistan",
    code: "AF",
    dial_code: "+93",
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    currency_name: "Afghan afghani",
    currency_symbol: "؋",
  },
  {
    name: "Åland Islands",
    code: "AX",
    dial_code: "+35818",
    flag: "https://flagcdn.com/ax.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Albania",
    code: "AL",
    dial_code: "+355",
    flag: "https://flagcdn.com/al.svg",
    currency_name: "Albanian lek",
    currency_symbol: "L",
  },
  {
    name: "Algeria",
    code: "DZ",
    dial_code: "+213",
    flag: "https://flagcdn.com/dz.svg",
    currency_name: "Algerian dinar",
    currency_symbol: "د.ج",
  },
  {
    name: "American Samoa",
    code: "AS",
    dial_code: "+1684",
    flag: "https://flagcdn.com/as.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Andorra",
    code: "AD",
    dial_code: "+376",
    flag: "https://flagcdn.com/ad.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Angola",
    code: "AO",
    dial_code: "+244",
    flag: "https://flagcdn.com/ao.svg",
    currency_name: "Angolan kwanza",
    currency_symbol: "Kz",
  },
  {
    name: "Anguilla",
    code: "AI",
    dial_code: "+1264",
    flag: "https://flagcdn.com/ai.svg",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Antarctica",
    code: "AQ",
    dial_code: "undefined",
    flag: "https://flagcdn.com/aq.svg",
    currency_name: "",
    currency_symbol: "",
  },
  {
    name: "Antigua and Barbuda",
    code: "AG",
    dial_code: "+1268",
    flag: "https://flagcdn.com/ag.svg",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Argentina",
    code: "AR",
    dial_code: "+54",
    flag: "https://flagcdn.com/ar.svg",
    currency_name: "Argentine peso",
    currency_symbol: "$",
  },
  {
    name: "Armenia",
    code: "AM",
    dial_code: "+374",
    flag: "https://flagcdn.com/am.svg",
    currency_name: "Armenian dram",
    currency_symbol: "֏",
  },
  {
    name: "Aruba",
    code: "AW",
    dial_code: "+297",
    flag: "https://flagcdn.com/aw.svg",
    currency_name: "Aruban florin",
    currency_symbol: "ƒ",
  },
  {
    name: "Australia",
    code: "AU",
    dial_code: "+61",
    flag: "https://flagcdn.com/au.svg",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Austria",
    code: "AT",
    dial_code: "+43",
    flag: "https://flagcdn.com/at.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    dial_code: "+994",
    flag: "https://flagcdn.com/az.svg",
    currency_name: "Azerbaijani manat",
    currency_symbol: "₼",
  },
  {
    name: "Bahamas",
    code: "BS",
    dial_code: "+1242",
    flag: "https://flagcdn.com/bs.svg",
    currency_name: "Bahamian dollar",
    currency_symbol: "$",
  },
  {
    name: "Bahrain",
    code: "BH",
    dial_code: "+973",
    flag: "https://flagcdn.com/bh.svg",
    currency_name: "Bahraini dinar",
    currency_symbol: ".د.ب",
  },
  {
    name: "Bangladesh",
    code: "BD",
    dial_code: "+880",
    flag: "https://flagcdn.com/bd.svg",
    currency_name: "Bangladeshi taka",
    currency_symbol: "৳",
  },
  {
    name: "Barbados",
    code: "BB",
    dial_code: "+1246",
    flag: "https://flagcdn.com/bb.svg",
    currency_name: "Barbadian dollar",
    currency_symbol: "$",
  },
  {
    name: "Belarus",
    code: "BY",
    dial_code: "+375",
    flag: "https://flagcdn.com/by.svg",
    currency_name: "Belarusian ruble",
    currency_symbol: "Br",
  },
  {
    name: "Belgium",
    code: "BE",
    dial_code: "+32",
    flag: "https://flagcdn.com/be.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Belize",
    code: "BZ",
    dial_code: "+501",
    flag: "https://flagcdn.com/bz.svg",
    currency_name: "Belize dollar",
    currency_symbol: "$",
  },
  {
    name: "Benin",
    code: "BJ",
    dial_code: "+229",
    flag: "https://flagcdn.com/bj.svg",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Bermuda",
    code: "BM",
    dial_code: "+1441",
    flag: "https://flagcdn.com/bm.svg",
    currency_name: "Bermudian dollar",
    currency_symbol: "$",
  },
  {
    name: "Bhutan",
    code: "BT",
    dial_code: "+975",
    flag: "https://flagcdn.com/bt.svg",
    currency_name: "Bhutanese ngultrum",
    currency_symbol: "Nu.",
  },
  {
    name: "Bolivia",
    code: "BO",
    dial_code: "+591",
    flag: "https://flagcdn.com/bo.svg",
    currency_name: "Bolivian boliviano",
    currency_symbol: "Bs.",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    dial_code: "+387",
    flag: "https://flagcdn.com/ba.svg",
    currency_name: "Bosnia and Herzegovina convertible mark",
    currency_symbol: "KM",
  },
  {
    name: "Botswana",
    code: "BW",
    dial_code: "+267",
    flag: "https://flagcdn.com/bw.svg",
    currency_name: "Botswana pula",
    currency_symbol: "P",
  },
  {
    name: "Bouvet Island",
    code: "BV",
    dial_code: "+47",
    flag: "https://flagcdn.com/bv.svg",
    currency_name: "",
    currency_symbol: "",
  },
  {
    name: "Brazil",
    code: "BR",
    dial_code: "+55",
    flag: "https://flagcdn.com/br.svg",
    currency_name: "Brazilian real",
    currency_symbol: "R$",
  },
  {
    name: "British Indian Ocean Territory",
    code: "IO",
    dial_code: "+246",
    flag: "https://flagcdn.com/io.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "British Virgin Islands",
    code: "VG",
    dial_code: "+1284",
    flag: "https://flagcdn.com/vg.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Brunei",
    code: "BN",
    dial_code: "+673",
    flag: "https://flagcdn.com/bn.svg",
    currency_name: "Brunei dollar",
    currency_symbol: "$",
  },
  {
    name: "Bulgaria",
    code: "BG",
    dial_code: "+359",
    flag: "https://flagcdn.com/bg.svg",
    currency_name: "Bulgarian lev",
    currency_symbol: "лв",
  },
  {
    name: "Burkina Faso",
    code: "BF",
    dial_code: "+226",
    flag: "https://flagcdn.com/bf.svg",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Burundi",
    code: "BI",
    dial_code: "+257",
    flag: "https://flagcdn.com/bi.svg",
    currency_name: "Burundian franc",
    currency_symbol: "Fr",
  },
  {
    name: "Cambodia",
    code: "KH",
    dial_code: "+855",
    flag: "https://flagcdn.com/kh.svg",
    currency_name: "Cambodian riel",
    currency_symbol: "៛",
  },
  {
    name: "Cameroon",
    code: "CM",
    dial_code: "+237",
    flag: "https://flagcdn.com/cm.svg",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Canada",
    code: "CA",
    dial_code: "+1",
    flag: "https://flagcdn.com/ca.svg",
    currency_name: "Canadian dollar",
    currency_symbol: "$",
  },
  {
    name: "Cape Verde",
    code: "CV",
    dial_code: "+238",
    flag: "https://flagcdn.com/cv.svg",
    currency_name: "Cape Verdean escudo",
    currency_symbol: "Esc",
  },
  {
    name: "Caribbean Netherlands",
    code: "BQ",
    dial_code: "+599",
    flag: "https://flagcdn.com/bq.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    dial_code: "+1345",
    flag: "https://flagcdn.com/ky.svg",
    currency_name: "Cayman Islands dollar",
    currency_symbol: "$",
  },
  {
    name: "Central African Republic",
    code: "CF",
    dial_code: "+236",
    flag: "https://flagcdn.com/cf.svg",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Chad",
    code: "TD",
    dial_code: "+235",
    flag: "https://flagcdn.com/td.svg",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Chile",
    code: "CL",
    dial_code: "+56",
    flag: "https://flagcdn.com/cl.svg",
    currency_name: "Chilean peso",
    currency_symbol: "$",
  },
  {
    name: "China",
    code: "CN",
    dial_code: "+86",
    flag: "https://flagcdn.com/cn.svg",
    currency_name: "Chinese yuan",
    currency_symbol: "¥",
  },
  {
    name: "Christmas Island",
    code: "CX",
    dial_code: "+61",
    flag: "https://flagcdn.com/cx.svg",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Cocos (Keeling) Islands",
    code: "CC",
    dial_code: "+61",
    flag: "https://flagcdn.com/cc.svg",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Colombia",
    code: "CO",
    dial_code: "+57",
    flag: "https://flagcdn.com/co.svg",
    currency_name: "Colombian peso",
    currency_symbol: "$",
  },
  {
    name: "Comoros",
    code: "KM",
    dial_code: "+269",
    flag: "https://flagcdn.com/km.svg",
    currency_name: "Comorian franc",
    currency_symbol: "Fr",
  },
  {
    name: "Cook Islands",
    code: "CK",
    dial_code: "+682",
    flag: "https://flagcdn.com/ck.svg",
    currency_name: "Cook Islands dollar",
    currency_symbol: "$",
  },
  {
    name: "Costa Rica",
    code: "CR",
    dial_code: "+506",
    flag: "https://flagcdn.com/cr.svg",
    currency_name: "Costa Rican colón",
    currency_symbol: "₡",
  },
  {
    name: "Croatia",
    code: "HR",
    dial_code: "+385",
    flag: "https://flagcdn.com/hr.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Cuba",
    code: "CU",
    dial_code: "+53",
    flag: "https://flagcdn.com/cu.svg",
    currency_name: "Cuban convertible peso",
    currency_symbol: "$",
  },
  {
    name: "Curaçao",
    code: "CW",
    dial_code: "+599",
    flag: "https://flagcdn.com/cw.svg",
    currency_name: "Netherlands Antillean guilder",
    currency_symbol: "ƒ",
  },
  {
    name: "Cyprus",
    code: "CY",
    dial_code: "+357",
    flag: "https://flagcdn.com/cy.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Czechia",
    code: "CZ",
    dial_code: "+420",
    flag: "https://flagcdn.com/cz.svg",
    currency_name: "Czech koruna",
    currency_symbol: "Kč",
  },
  {
    name: "Denmark",
    code: "DK",
    dial_code: "+45",
    flag: "https://flagcdn.com/dk.svg",
    currency_name: "Danish krone",
    currency_symbol: "kr",
  },
  {
    name: "Djibouti",
    code: "DJ",
    dial_code: "+253",
    flag: "https://flagcdn.com/dj.svg",
    currency_name: "Djiboutian franc",
    currency_symbol: "Fr",
  },
  {
    name: "Dominica",
    code: "DM",
    dial_code: "+1767",
    flag: "https://flagcdn.com/dm.svg",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    dial_code: "+1809",
    flag: "https://flagcdn.com/do.svg",
    currency_name: "Dominican peso",
    currency_symbol: "$",
  },
  {
    name: "DR Congo",
    code: "CD",
    dial_code: "+243",
    flag: "https://flagcdn.com/cd.svg",
    currency_name: "Congolese franc",
    currency_symbol: "FC",
  },
  {
    name: "Ecuador",
    code: "EC",
    dial_code: "+593",
    flag: "https://flagcdn.com/ec.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Egypt",
    code: "EG",
    dial_code: "+20",
    flag: "https://flagcdn.com/eg.svg",
    currency_name: "Egyptian pound",
    currency_symbol: "£",
  },
  {
    name: "El Salvador",
    code: "SV",
    dial_code: "+503",
    flag: "https://flagcdn.com/sv.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Equatorial Guinea",
    code: "GQ",
    dial_code: "+240",
    flag: "https://flagcdn.com/gq.svg",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Eritrea",
    code: "ER",
    dial_code: "+291",
    flag: "https://flagcdn.com/er.svg",
    currency_name: "Eritrean nakfa",
    currency_symbol: "Nfk",
  },
  {
    name: "Estonia",
    code: "EE",
    dial_code: "+372",
    flag: "https://flagcdn.com/ee.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Eswatini",
    code: "SZ",
    dial_code: "+268",
    flag: "https://flagcdn.com/sz.svg",
    currency_name: "Swazi lilangeni",
    currency_symbol: "L",
  },
  {
    name: "Ethiopia",
    code: "ET",
    dial_code: "+251",
    flag: "https://flagcdn.com/et.svg",
    currency_name: "Ethiopian birr",
    currency_symbol: "Br",
  },
  {
    name: "Falkland Islands",
    code: "FK",
    dial_code: "+500",
    flag: "https://flagcdn.com/fk.svg",
    currency_name: "Falkland Islands pound",
    currency_symbol: "£",
  },
  {
    name: "Faroe Islands",
    code: "FO",
    dial_code: "+298",
    flag: "https://flagcdn.com/fo.svg",
    currency_name: "Danish krone",
    currency_symbol: "kr",
  },
  {
    name: "Fiji",
    code: "FJ",
    dial_code: "+679",
    flag: "https://flagcdn.com/fj.svg",
    currency_name: "Fijian dollar",
    currency_symbol: "$",
  },
  {
    name: "Finland",
    code: "FI",
    dial_code: "+358",
    flag: "https://flagcdn.com/fi.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "France",
    code: "FR",
    dial_code: "+33",
    flag: "https://flagcdn.com/fr.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "French Guiana",
    code: "GF",
    dial_code: "+594",
    flag: "https://flagcdn.com/gf.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "French Polynesia",
    code: "PF",
    dial_code: "+689",
    flag: "https://flagcdn.com/pf.svg",
    currency_name: "CFP franc",
    currency_symbol: "₣",
  },
  {
    name: "French Southern and Antarctic Lands",
    code: "TF",
    dial_code: "+262",
    flag: "https://flagcdn.com/tf.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Gabon",
    code: "GA",
    dial_code: "+241",
    flag: "https://flagcdn.com/ga.svg",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Gambia",
    code: "GM",
    dial_code: "+220",
    flag: "https://flagcdn.com/gm.svg",
    currency_name: "dalasi",
    currency_symbol: "D",
  },
  {
    name: "Georgia",
    code: "GE",
    dial_code: "+995",
    flag: "https://flagcdn.com/ge.svg",
    currency_name: "lari",
    currency_symbol: "₾",
  },
  {
    name: "Germany",
    code: "DE",
    dial_code: "+49",
    flag: "https://flagcdn.com/de.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Ghana",
    code: "GH",
    dial_code: "+233",
    flag: "https://flagcdn.com/gh.svg",
    currency_name: "Ghanaian cedi",
    currency_symbol: "₵",
  },
  {
    name: "Gibraltar",
    code: "GI",
    dial_code: "+350",
    flag: "https://flagcdn.com/gi.svg",
    currency_name: "Gibraltar pound",
    currency_symbol: "£",
  },
  {
    name: "Greece",
    code: "GR",
    dial_code: "+30",
    flag: "https://flagcdn.com/gr.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Greenland",
    code: "GL",
    dial_code: "+299",
    flag: "https://flagcdn.com/gl.svg",
    currency_name: "krone",
    currency_symbol: "kr.",
  },
  {
    name: "Grenada",
    code: "GD",
    dial_code: "+1473",
    flag: "https://flagcdn.com/gd.svg",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Guadeloupe",
    code: "GP",
    dial_code: "+590",
    flag: "https://flagcdn.com/gp.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Guam",
    code: "GU",
    dial_code: "+1671",
    flag: "https://flagcdn.com/gu.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Guatemala",
    code: "GT",
    dial_code: "+502",
    flag: "https://flagcdn.com/gt.svg",
    currency_name: "Guatemalan quetzal",
    currency_symbol: "Q",
  },
  {
    name: "Guernsey",
    code: "GG",
    dial_code: "+44",
    flag: "https://flagcdn.com/gg.svg",
    currency_name: "British pound",
    currency_symbol: "£",
  },
  {
    name: "Guinea",
    code: "GN",
    dial_code: "+224",
    flag: "https://flagcdn.com/gn.svg",
    currency_name: "Guinean franc",
    currency_symbol: "Fr",
  },
  {
    name: "Guinea-Bissau",
    code: "GW",
    dial_code: "+245",
    flag: "https://flagcdn.com/gw.svg",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Guyana",
    code: "GY",
    dial_code: "+592",
    flag: "https://flagcdn.com/gy.svg",
    currency_name: "Guyanese dollar",
    currency_symbol: "$",
  },
  {
    name: "Haiti",
    code: "HT",
    dial_code: "+509",
    flag: "https://flagcdn.com/ht.svg",
    currency_name: "Haitian gourde",
    currency_symbol: "G",
  },
  {
    name: "Heard Island and McDonald Islands",
    code: "HM",
    dial_code: "undefined",
    flag: "https://flagcdn.com/hm.svg",
    currency_name: "",
    currency_symbol: "",
  },
  {
    name: "Honduras",
    code: "HN",
    dial_code: "+504",
    flag: "https://flagcdn.com/hn.svg",
    currency_name: "Honduran lempira",
    currency_symbol: "L",
  },
  {
    name: "Hong Kong",
    code: "HK",
    dial_code: "+852",
    flag: "https://flagcdn.com/hk.svg",
    currency_name: "Hong Kong dollar",
    currency_symbol: "$",
  },
  {
    name: "Hungary",
    code: "HU",
    dial_code: "+36",
    flag: "https://flagcdn.com/hu.svg",
    currency_name: "Hungarian forint",
    currency_symbol: "Ft",
  },
  {
    name: "Iceland",
    code: "IS",
    dial_code: "+354",
    flag: "https://flagcdn.com/is.svg",
    currency_name: "Icelandic króna",
    currency_symbol: "kr",
  },
  {
    name: "India",
    code: "IN",
    dial_code: "+91",
    flag: "https://flagcdn.com/in.svg",
    currency_name: "Indian rupee",
    currency_symbol: "₹",
  },
  {
    name: "Indonesia",
    code: "ID",
    dial_code: "+62",
    flag: "https://flagcdn.com/id.svg",
    currency_name: "Indonesian rupiah",
    currency_symbol: "Rp",
  },
  {
    name: "Iran",
    code: "IR",
    dial_code: "+98",
    flag: "https://flagcdn.com/ir.svg",
    currency_name: "Iranian rial",
    currency_symbol: "﷼",
  },
  {
    name: "Iraq",
    code: "IQ",
    dial_code: "+964",
    flag: "https://flagcdn.com/iq.svg",
    currency_name: "Iraqi dinar",
    currency_symbol: "ع.د",
  },
  {
    name: "Ireland",
    code: "IE",
    dial_code: "+353",
    flag: "https://flagcdn.com/ie.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Isle of Man",
    code: "IM",
    dial_code: "+44",
    flag: "https://flagcdn.com/im.svg",
    currency_name: "British pound",
    currency_symbol: "£",
  },
  {
    name: "Israel",
    code: "IL",
    dial_code: "+972",
    flag: "https://flagcdn.com/il.svg",
    currency_name: "Israeli new shekel",
    currency_symbol: "₪",
  },
  {
    name: "Italy",
    code: "IT",
    dial_code: "+39",
    flag: "https://flagcdn.com/it.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Ivory Coast",
    code: "CI",
    dial_code: "+225",
    flag: "https://flagcdn.com/ci.svg",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Jamaica",
    code: "JM",
    dial_code: "+1876",
    flag: "https://flagcdn.com/jm.svg",
    currency_name: "Jamaican dollar",
    currency_symbol: "$",
  },
  {
    name: "Japan",
    code: "JP",
    dial_code: "+81",
    flag: "https://flagcdn.com/jp.svg",
    currency_name: "Japanese yen",
    currency_symbol: "¥",
  },
  {
    name: "Jersey",
    code: "JE",
    dial_code: "+44",
    flag: "https://flagcdn.com/je.svg",
    currency_name: "British pound",
    currency_symbol: "£",
  },
  {
    name: "Jordan",
    code: "JO",
    dial_code: "+962",
    flag: "https://flagcdn.com/jo.svg",
    currency_name: "Jordanian dinar",
    currency_symbol: "د.ا",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    dial_code: "+76",
    flag: "https://flagcdn.com/kz.svg",
    currency_name: "Kazakhstani tenge",
    currency_symbol: "₸",
  },
  {
    name: "Kenya",
    code: "KE",
    dial_code: "+254",
    flag: "https://flagcdn.com/ke.svg",
    currency_name: "Kenyan shilling",
    currency_symbol: "Sh",
  },
  {
    name: "Kiribati",
    code: "KI",
    dial_code: "+686",
    flag: "https://flagcdn.com/ki.svg",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Kosovo",
    code: "XK",
    dial_code: "+383",
    flag: "https://flagcdn.com/xk.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Kuwait",
    code: "KW",
    dial_code: "+965",
    flag: "https://flagcdn.com/kw.svg",
    currency_name: "Kuwaiti dinar",
    currency_symbol: "د.ك",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    dial_code: "+996",
    flag: "https://flagcdn.com/kg.svg",
    currency_name: "Kyrgyzstani som",
    currency_symbol: "с",
  },
  {
    name: "Laos",
    code: "LA",
    dial_code: "+856",
    flag: "https://flagcdn.com/la.svg",
    currency_name: "Lao kip",
    currency_symbol: "₭",
  },
  {
    name: "Latvia",
    code: "LV",
    dial_code: "+371",
    flag: "https://flagcdn.com/lv.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Lebanon",
    code: "LB",
    dial_code: "+961",
    flag: "https://flagcdn.com/lb.svg",
    currency_name: "Lebanese pound",
    currency_symbol: "ل.ل",
  },
  {
    name: "Lesotho",
    code: "LS",
    dial_code: "+266",
    flag: "https://flagcdn.com/ls.svg",
    currency_name: "Lesotho loti",
    currency_symbol: "L",
  },
  {
    name: "Liberia",
    code: "LR",
    dial_code: "+231",
    flag: "https://flagcdn.com/lr.svg",
    currency_name: "Liberian dollar",
    currency_symbol: "$",
  },
  {
    name: "Libya",
    code: "LY",
    dial_code: "+218",
    flag: "https://flagcdn.com/ly.svg",
    currency_name: "Libyan dinar",
    currency_symbol: "ل.د",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    dial_code: "+423",
    flag: "https://flagcdn.com/li.svg",
    currency_name: "Swiss franc",
    currency_symbol: "Fr",
  },
  {
    name: "Lithuania",
    code: "LT",
    dial_code: "+370",
    flag: "https://flagcdn.com/lt.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Luxembourg",
    code: "LU",
    dial_code: "+352",
    flag: "https://flagcdn.com/lu.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Macau",
    code: "MO",
    dial_code: "+853",
    flag: "https://flagcdn.com/mo.svg",
    currency_name: "Macanese pataca",
    currency_symbol: "P",
  },
  {
    name: "Madagascar",
    code: "MG",
    dial_code: "+261",
    flag: "https://flagcdn.com/mg.svg",
    currency_name: "Malagasy ariary",
    currency_symbol: "Ar",
  },
  {
    name: "Malawi",
    code: "MW",
    dial_code: "+265",
    flag: "https://flagcdn.com/mw.svg",
    currency_name: "Malawian kwacha",
    currency_symbol: "MK",
  },
  {
    name: "Malaysia",
    code: "MY",
    dial_code: "+60",
    flag: "https://flagcdn.com/my.svg",
    currency_name: "Malaysian ringgit",
    currency_symbol: "RM",
  },
  {
    name: "Maldives",
    code: "MV",
    dial_code: "+960",
    flag: "https://flagcdn.com/mv.svg",
    currency_name: "Maldivian rufiyaa",
    currency_symbol: ".ރ",
  },
  {
    name: "Mali",
    code: "ML",
    dial_code: "+223",
    flag: "https://flagcdn.com/ml.svg",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Malta",
    code: "MT",
    dial_code: "+356",
    flag: "https://flagcdn.com/mt.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Marshall Islands",
    code: "MH",
    dial_code: "+692",
    flag: "https://flagcdn.com/mh.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Martinique",
    code: "MQ",
    dial_code: "+596",
    flag: "https://flagcdn.com/mq.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Mauritania",
    code: "MR",
    dial_code: "+222",
    flag: "https://flagcdn.com/mr.svg",
    currency_name: "Mauritanian ouguiya",
    currency_symbol: "UM",
  },
  {
    name: "Mauritius",
    code: "MU",
    dial_code: "+230",
    flag: "https://flagcdn.com/mu.svg",
    currency_name: "Mauritian rupee",
    currency_symbol: "₨",
  },
  {
    name: "Mayotte",
    code: "YT",
    dial_code: "+262",
    flag: "https://flagcdn.com/yt.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Mexico",
    code: "MX",
    dial_code: "+52",
    flag: "https://flagcdn.com/mx.svg",
    currency_name: "Mexican peso",
    currency_symbol: "$",
  },
  {
    name: "Micronesia",
    code: "FM",
    dial_code: "+691",
    flag: "https://flagcdn.com/fm.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Moldova",
    code: "MD",
    dial_code: "+373",
    flag: "https://flagcdn.com/md.svg",
    currency_name: "Moldovan leu",
    currency_symbol: "L",
  },
  {
    name: "Monaco",
    code: "MC",
    dial_code: "+377",
    flag: "https://flagcdn.com/mc.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Mongolia",
    code: "MN",
    dial_code: "+976",
    flag: "https://flagcdn.com/mn.svg",
    currency_name: "Mongolian tögrög",
    currency_symbol: "₮",
  },
  {
    name: "Montenegro",
    code: "ME",
    dial_code: "+382",
    flag: "https://flagcdn.com/me.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Montserrat",
    code: "MS",
    dial_code: "+1664",
    flag: "https://flagcdn.com/ms.svg",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Morocco",
    code: "MA",
    dial_code: "+212",
    flag: "https://flagcdn.com/ma.svg",
    currency_name: "Moroccan dirham",
    currency_symbol: "د.م.",
  },
  {
    name: "Mozambique",
    code: "MZ",
    dial_code: "+258",
    flag: "https://flagcdn.com/mz.svg",
    currency_name: "Mozambican metical",
    currency_symbol: "MT",
  },
  {
    name: "Myanmar",
    code: "MM",
    dial_code: "+95",
    flag: "https://flagcdn.com/mm.svg",
    currency_name: "Burmese kyat",
    currency_symbol: "Ks",
  },
  {
    name: "Namibia",
    code: "NA",
    dial_code: "+264",
    flag: "https://flagcdn.com/na.svg",
    currency_name: "Namibian dollar",
    currency_symbol: "$",
  },
  {
    name: "Nauru",
    code: "NR",
    dial_code: "+674",
    flag: "https://flagcdn.com/nr.svg",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Nepal",
    code: "NP",
    dial_code: "+977",
    flag: "https://flagcdn.com/np.svg",
    currency_name: "Nepalese rupee",
    currency_symbol: "₨",
  },
  {
    name: "Netherlands",
    code: "NL",
    dial_code: "+31",
    flag: "https://flagcdn.com/nl.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "New Caledonia",
    code: "NC",
    dial_code: "+687",
    flag: "https://flagcdn.com/nc.svg",
    currency_name: "CFP franc",
    currency_symbol: "₣",
  },
  {
    name: "New Zealand",
    code: "NZ",
    dial_code: "+64",
    flag: "https://flagcdn.com/nz.svg",
    currency_name: "New Zealand dollar",
    currency_symbol: "$",
  },
  {
    name: "Nicaragua",
    code: "NI",
    dial_code: "+505",
    flag: "https://flagcdn.com/ni.svg",
    currency_name: "Nicaraguan córdoba",
    currency_symbol: "C$",
  },
  {
    name: "Niger",
    code: "NE",
    dial_code: "+227",
    flag: "https://flagcdn.com/ne.svg",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Nigeria",
    code: "NG",
    dial_code: "+234",
    flag: "https://flagcdn.com/ng.svg",
    currency_name: "Nigerian naira",
    currency_symbol: "₦",
  },
  {
    name: "Niue",
    code: "NU",
    dial_code: "+683",
    flag: "https://flagcdn.com/nu.svg",
    currency_name: "New Zealand dollar",
    currency_symbol: "$",
  },
  {
    name: "Norfolk Island",
    code: "NF",
    dial_code: "+672",
    flag: "https://flagcdn.com/nf.svg",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "North Korea",
    code: "KP",
    dial_code: "+850",
    flag: "https://flagcdn.com/kp.svg",
    currency_name: "North Korean won",
    currency_symbol: "₩",
  },
  {
    name: "North Macedonia",
    code: "MK",
    dial_code: "+389",
    flag: "https://flagcdn.com/mk.svg",
    currency_name: "denar",
    currency_symbol: "den",
  },
  {
    name: "Northern Mariana Islands",
    code: "MP",
    dial_code: "+1670",
    flag: "https://flagcdn.com/mp.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Norway",
    code: "NO",
    dial_code: "+47",
    flag: "https://flagcdn.com/no.svg",
    currency_name: "Norwegian krone",
    currency_symbol: "kr",
  },
  {
    name: "Oman",
    code: "OM",
    dial_code: "+968",
    flag: "https://flagcdn.com/om.svg",
    currency_name: "Omani rial",
    currency_symbol: "ر.ع.",
  },
  {
    name: "Pakistan",
    code: "PK",
    dial_code: "+92",
    flag: "https://flagcdn.com/pk.svg",
    currency_name: "Pakistani rupee",
    currency_symbol: "₨",
  },
  {
    name: "Palau",
    code: "PW",
    dial_code: "+680",
    flag: "https://flagcdn.com/pw.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Palestine",
    code: "PS",
    dial_code: "+970",
    flag: "https://flagcdn.com/ps.svg",
    currency_name: "Egyptian pound",
    currency_symbol: "E£",
  },
  {
    name: "Panama",
    code: "PA",
    dial_code: "+507",
    flag: "https://flagcdn.com/pa.svg",
    currency_name: "Panamanian balboa",
    currency_symbol: "B/.",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    dial_code: "+675",
    flag: "https://flagcdn.com/pg.svg",
    currency_name: "Papua New Guinean kina",
    currency_symbol: "K",
  },
  {
    name: "Paraguay",
    code: "PY",
    dial_code: "+595",
    flag: "https://flagcdn.com/py.svg",
    currency_name: "Paraguayan guaraní",
    currency_symbol: "₲",
  },
  {
    name: "Peru",
    code: "PE",
    dial_code: "+51",
    flag: "https://flagcdn.com/pe.svg",
    currency_name: "Peruvian sol",
    currency_symbol: "S/ ",
  },
  {
    name: "Philippines",
    code: "PH",
    dial_code: "+63",
    flag: "https://flagcdn.com/ph.svg",
    currency_name: "Philippine peso",
    currency_symbol: "₱",
  },
  {
    name: "Pitcairn Islands",
    code: "PN",
    dial_code: "+64",
    flag: "https://flagcdn.com/pn.svg",
    currency_name: "New Zealand dollar",
    currency_symbol: "$",
  },
  {
    name: "Poland",
    code: "PL",
    dial_code: "+48",
    flag: "https://flagcdn.com/pl.svg",
    currency_name: "Polish złoty",
    currency_symbol: "zł",
  },
  {
    name: "Portugal",
    code: "PT",
    dial_code: "+351",
    flag: "https://flagcdn.com/pt.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Puerto Rico",
    code: "PR",
    dial_code: "+1787",
    flag: "https://flagcdn.com/pr.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Qatar",
    code: "QA",
    dial_code: "+974",
    flag: "https://flagcdn.com/qa.svg",
    currency_name: "Qatari riyal",
    currency_symbol: "ر.ق",
  },
  {
    name: "Republic of the Congo",
    code: "CG",
    dial_code: "+242",
    flag: "https://flagcdn.com/cg.svg",
    currency_name: "Central African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Réunion",
    code: "RE",
    dial_code: "+262",
    flag: "https://flagcdn.com/re.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Romania",
    code: "RO",
    dial_code: "+40",
    flag: "https://flagcdn.com/ro.svg",
    currency_name: "Romanian leu",
    currency_symbol: "lei",
  },
  {
    name: "Russia",
    code: "RU",
    dial_code: "+73",
    flag: "https://flagcdn.com/ru.svg",
    currency_name: "Russian ruble",
    currency_symbol: "₽",
  },
  {
    name: "Rwanda",
    code: "RW",
    dial_code: "+250",
    flag: "https://flagcdn.com/rw.svg",
    currency_name: "Rwandan franc",
    currency_symbol: "Fr",
  },
  {
    name: "Saint Barthélemy",
    code: "BL",
    dial_code: "+590",
    flag: "https://flagcdn.com/bl.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    dial_code: "+290",
    flag: "https://flagcdn.com/sh.svg",
    currency_name: "Pound sterling",
    currency_symbol: "£",
  },
  {
    name: "Saint Kitts and Nevis",
    code: "KN",
    dial_code: "+1869",
    flag: "https://flagcdn.com/kn.svg",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Saint Lucia",
    code: "LC",
    dial_code: "+1758",
    flag: "https://flagcdn.com/lc.svg",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Saint Martin",
    code: "MF",
    dial_code: "+590",
    flag: "https://flagcdn.com/mf.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Saint Pierre and Miquelon",
    code: "PM",
    dial_code: "+508",
    flag: "https://flagcdn.com/pm.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Saint Vincent and the Grenadines",
    code: "VC",
    dial_code: "+1784",
    flag: "https://flagcdn.com/vc.svg",
    currency_name: "Eastern Caribbean dollar",
    currency_symbol: "$",
  },
  {
    name: "Samoa",
    code: "WS",
    dial_code: "+685",
    flag: "https://flagcdn.com/ws.svg",
    currency_name: "Samoan tālā",
    currency_symbol: "T",
  },
  {
    name: "San Marino",
    code: "SM",
    dial_code: "+378",
    flag: "https://flagcdn.com/sm.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "São Tomé and Príncipe",
    code: "ST",
    dial_code: "+239",
    flag: "https://flagcdn.com/st.svg",
    currency_name: "São Tomé and Príncipe dobra",
    currency_symbol: "Db",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    dial_code: "+966",
    flag: "https://flagcdn.com/sa.svg",
    currency_name: "Saudi riyal",
    currency_symbol: "ر.س",
  },
  {
    name: "Senegal",
    code: "SN",
    dial_code: "+221",
    flag: "https://flagcdn.com/sn.svg",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Serbia",
    code: "RS",
    dial_code: "+381",
    flag: "https://flagcdn.com/rs.svg",
    currency_name: "Serbian dinar",
    currency_symbol: "дин.",
  },
  {
    name: "Seychelles",
    code: "SC",
    dial_code: "+248",
    flag: "https://flagcdn.com/sc.svg",
    currency_name: "Seychellois rupee",
    currency_symbol: "₨",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    dial_code: "+232",
    flag: "https://flagcdn.com/sl.svg",
    currency_name: "Sierra Leonean leone",
    currency_symbol: "Le",
  },
  {
    name: "Singapore",
    code: "SG",
    dial_code: "+65",
    flag: "https://flagcdn.com/sg.svg",
    currency_name: "Singapore dollar",
    currency_symbol: "$",
  },
  {
    name: "Sint Maarten",
    code: "SX",
    dial_code: "+1721",
    flag: "https://flagcdn.com/sx.svg",
    currency_name: "Netherlands Antillean guilder",
    currency_symbol: "ƒ",
  },
  {
    name: "Slovakia",
    code: "SK",
    dial_code: "+421",
    flag: "https://flagcdn.com/sk.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Slovenia",
    code: "SI",
    dial_code: "+386",
    flag: "https://flagcdn.com/si.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    dial_code: "+677",
    flag: "https://flagcdn.com/sb.svg",
    currency_name: "Solomon Islands dollar",
    currency_symbol: "$",
  },
  {
    name: "Somalia",
    code: "SO",
    dial_code: "+252",
    flag: "https://flagcdn.com/so.svg",
    currency_name: "Somali shilling",
    currency_symbol: "Sh",
  },
  {
    name: "South Africa",
    code: "ZA",
    dial_code: "+27",
    flag: "https://flagcdn.com/za.svg",
    currency_name: "South African rand",
    currency_symbol: "R",
  },
  {
    name: "South Georgia",
    code: "GS",
    dial_code: "+500",
    flag: "https://flagcdn.com/gs.svg",
    currency_name: "Saint Helena pound",
    currency_symbol: "£",
  },
  {
    name: "South Korea",
    code: "KR",
    dial_code: "+82",
    flag: "https://flagcdn.com/kr.svg",
    currency_name: "South Korean won",
    currency_symbol: "₩",
  },
  {
    name: "South Sudan",
    code: "SS",
    dial_code: "+211",
    flag: "https://flagcdn.com/ss.svg",
    currency_name: "South Sudanese pound",
    currency_symbol: "£",
  },
  {
    name: "Spain",
    code: "ES",
    dial_code: "+34",
    flag: "https://flagcdn.com/es.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    dial_code: "+94",
    flag: "https://flagcdn.com/lk.svg",
    currency_name: "Sri Lankan rupee",
    currency_symbol: "Rs  රු",
  },
  {
    name: "Sudan",
    code: "SD",
    dial_code: "+249",
    flag: "https://flagcdn.com/sd.svg",
    currency_name: "Sudanese pound",
    currency_symbol: "ج.س",
  },
  {
    name: "Suriname",
    code: "SR",
    dial_code: "+597",
    flag: "https://flagcdn.com/sr.svg",
    currency_name: "Surinamese dollar",
    currency_symbol: "$",
  },
  {
    name: "Svalbard and Jan Mayen",
    code: "SJ",
    dial_code: "+4779",
    flag: "https://flagcdn.com/sj.svg",
    currency_name: "krone",
    currency_symbol: "kr",
  },
  {
    name: "Sweden",
    code: "SE",
    dial_code: "+46",
    flag: "https://flagcdn.com/se.svg",
    currency_name: "Swedish krona",
    currency_symbol: "kr",
  },
  {
    name: "Switzerland",
    code: "CH",
    dial_code: "+41",
    flag: "https://flagcdn.com/ch.svg",
    currency_name: "Swiss franc",
    currency_symbol: "Fr.",
  },
  {
    name: "Syria",
    code: "SY",
    dial_code: "+963",
    flag: "https://flagcdn.com/sy.svg",
    currency_name: "Syrian pound",
    currency_symbol: "£",
  },
  {
    name: "Taiwan",
    code: "TW",
    dial_code: "+886",
    flag: "https://flagcdn.com/tw.svg",
    currency_name: "New Taiwan dollar",
    currency_symbol: "$",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    dial_code: "+992",
    flag: "https://flagcdn.com/tj.svg",
    currency_name: "Tajikistani somoni",
    currency_symbol: "ЅМ",
  },
  {
    name: "Tanzania",
    code: "TZ",
    dial_code: "+255",
    flag: "https://flagcdn.com/tz.svg",
    currency_name: "Tanzanian shilling",
    currency_symbol: "Sh",
  },
  {
    name: "Thailand",
    code: "TH",
    dial_code: "+66",
    flag: "https://flagcdn.com/th.svg",
    currency_name: "Thai baht",
    currency_symbol: "฿",
  },
  {
    name: "Timor-Leste",
    code: "TL",
    dial_code: "+670",
    flag: "https://flagcdn.com/tl.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Togo",
    code: "TG",
    dial_code: "+228",
    flag: "https://flagcdn.com/tg.svg",
    currency_name: "West African CFA franc",
    currency_symbol: "Fr",
  },
  {
    name: "Tokelau",
    code: "TK",
    dial_code: "+690",
    flag: "https://flagcdn.com/tk.svg",
    currency_name: "New Zealand dollar",
    currency_symbol: "$",
  },
  {
    name: "Tonga",
    code: "TO",
    dial_code: "+676",
    flag: "https://flagcdn.com/to.svg",
    currency_name: "Tongan paʻanga",
    currency_symbol: "T$",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    dial_code: "+1868",
    flag: "https://flagcdn.com/tt.svg",
    currency_name: "Trinidad and Tobago dollar",
    currency_symbol: "$",
  },
  {
    name: "Tunisia",
    code: "TN",
    dial_code: "+216",
    flag: "https://flagcdn.com/tn.svg",
    currency_name: "Tunisian dinar",
    currency_symbol: "د.ت",
  },
  {
    name: "Turkey",
    code: "TR",
    dial_code: "+90",
    flag: "https://flagcdn.com/tr.svg",
    currency_name: "Turkish lira",
    currency_symbol: "₺",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    dial_code: "+993",
    flag: "https://flagcdn.com/tm.svg",
    currency_name: "Turkmenistan manat",
    currency_symbol: "m",
  },
  {
    name: "Turks and Caicos Islands",
    code: "TC",
    dial_code: "+1649",
    flag: "https://flagcdn.com/tc.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Tuvalu",
    code: "TV",
    dial_code: "+688",
    flag: "https://flagcdn.com/tv.svg",
    currency_name: "Australian dollar",
    currency_symbol: "$",
  },
  {
    name: "Uganda",
    code: "UG",
    dial_code: "+256",
    flag: "https://flagcdn.com/ug.svg",
    currency_name: "Ugandan shilling",
    currency_symbol: "Sh",
  },
  {
    name: "Ukraine",
    code: "UA",
    dial_code: "+380",
    flag: "https://flagcdn.com/ua.svg",
    currency_name: "Ukrainian hryvnia",
    currency_symbol: "₴",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    dial_code: "+971",
    flag: "https://flagcdn.com/ae.svg",
    currency_name: "United Arab Emirates dirham",
    currency_symbol: "د.إ",
  },
  {
    name: "United Kingdom",
    code: "GB",
    dial_code: "+44",
    flag: "https://flagcdn.com/gb.svg",
    currency_name: "British pound",
    currency_symbol: "£",
  },
  {
    name: "United States",
    code: "US",
    dial_code: "+1201",
    flag: "https://flagcdn.com/us.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "United States Minor Outlying Islands",
    code: "UM",
    dial_code: "+268",
    flag: "https://flagcdn.com/um.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "United States Virgin Islands",
    code: "VI",
    dial_code: "+1340",
    flag: "https://flagcdn.com/vi.svg",
    currency_name: "United States dollar",
    currency_symbol: "$",
  },
  {
    name: "Uruguay",
    code: "UY",
    dial_code: "+598",
    flag: "https://flagcdn.com/uy.svg",
    currency_name: "Uruguayan peso",
    currency_symbol: "$",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    dial_code: "+998",
    flag: "https://flagcdn.com/uz.svg",
    currency_name: "Uzbekistani soʻm",
    currency_symbol: "so'm",
  },
  {
    name: "Vanuatu",
    code: "VU",
    dial_code: "+678",
    flag: "https://flagcdn.com/vu.svg",
    currency_name: "Vanuatu vatu",
    currency_symbol: "Vt",
  },
  {
    name: "Vatican City",
    code: "VA",
    dial_code: "+3906698",
    flag: "https://flagcdn.com/va.svg",
    currency_name: "Euro",
    currency_symbol: "€",
  },
  {
    name: "Venezuela",
    code: "VE",
    dial_code: "+58",
    flag: "https://flagcdn.com/ve.svg",
    currency_name: "Venezuelan bolívar soberano",
    currency_symbol: "Bs.S.",
  },
  {
    name: "Vietnam",
    code: "VN",
    dial_code: "+84",
    flag: "https://flagcdn.com/vn.svg",
    currency_name: "Vietnamese đồng",
    currency_symbol: "₫",
  },
  {
    name: "Wallis and Futuna",
    code: "WF",
    dial_code: "+681",
    flag: "https://flagcdn.com/wf.svg",
    currency_name: "CFP franc",
    currency_symbol: "₣",
  },
  {
    name: "Western Sahara",
    code: "EH",
    dial_code: "+2125288",
    flag: "https://flagcdn.com/eh.svg",
    currency_name: "Algerian dinar",
    currency_symbol: "دج",
  },
  {
    name: "Yemen",
    code: "YE",
    dial_code: "+967",
    flag: "https://flagcdn.com/ye.svg",
    currency_name: "Yemeni rial",
    currency_symbol: "﷼",
  },
  {
    name: "Zambia",
    code: "ZM",
    dial_code: "+260",
    flag: "https://flagcdn.com/zm.svg",
    currency_name: "Zambian kwacha",
    currency_symbol: "ZK",
  },
  {
    name: "Zimbabwe",
    code: "ZW",
    dial_code: "+263",
    flag: "https://flagcdn.com/zw.svg",
    currency_name: "Zimbabwean dollar",
    currency_symbol: "$",
  },
];
