export const onrampCoverageData = {
  AFG: {
    name: "Afghanistan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  AGO: {
    name: "Angola",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ALB: {
    name: "Albania",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ARE: {
    name: "United Arab Emirates",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ARG: {
    name: "Argentina",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ARM: {
    name: "Armenia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ATF: {
    name: "French Southern Territories",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  AUS: {
    name: "Australia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  AUT: {
    name: "Austria",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  AZE: {
    name: "Azerbaijan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BDI: {
    name: "Burundi",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BEL: {
    name: "Belgium",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BEN: {
    name: "Benin",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BFA: {
    name: "Burkina Faso",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BGD: {
    name: "Bangladesh",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BGR: {
    name: "Bulgaria",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BHS: {
    name: "Bahamas",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BIH: {
    name: "Bosnia and Herzegovina",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BLR: {
    name: "Belarus",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BLZ: {
    name: "Belize",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BOL: {
    name: "Bolivia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BRA: {
    name: "Brazil",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BRN: {
    name: "Brunei",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BTN: {
    name: "Bhutan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BWA: {
    name: "Botswana",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CAF: {
    name: "Central African Republic",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CAN: {
    name: "Canada",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CHE: {
    name: "Switzerland",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CHL: {
    name: "Chile",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CHN: {
    name: "China",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CIV: {
    name: "Cote d'Ivoire",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CMR: {
    name: "Cameroon",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  COD: {
    name: "Democratic Republic of Congo",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  COG: {
    name: "Congo",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  COL: {
    name: "Colombia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CRI: {
    name: "Costa Rica",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CUB: {
    name: "Cuba",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CYP: {
    name: "Cyprus",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CZE: {
    name: "Czechia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  DEU: {
    name: "Germany",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  DJI: {
    name: "Djibouti",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  DNK: {
    name: "Denmark",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GRL: {
    name: "Greenland",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  DOM: {
    name: "Dominican Republic",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  DZA: {
    name: "Algeria",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ECU: {
    name: "Ecuador",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  EGY: {
    name: "Egypt",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ERI: {
    name: "Eritrea",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ESP: {
    name: "Spain",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  EST: {
    name: "Estonia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ETH: {
    name: "Ethiopia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  FIN: {
    name: "Finland",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  FJI: {
    name: "Fiji",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  FRA: {
    name: "France",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GUF: {
    name: "French Guiana",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GAB: {
    name: "Gabon",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GBR: {
    name: "United Kingdom",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GEO: {
    name: "Georgia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GHA: {
    name: "Ghana",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GIN: {
    name: "Guinea",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GMB: {
    name: "Gambia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GNB: {
    name: "Guinea-Bissau",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GNQ: {
    name: "Equatorial Guinea",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GRC: {
    name: "Greece",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GTM: {
    name: "Guatemala",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GUY: {
    name: "Guyana",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  HND: {
    name: "Honduras",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  HRV: {
    name: "Croatia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  HTI: {
    name: "Haiti",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  HUN: {
    name: "Hungary",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  IDN: {
    name: "Indonesia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  IND: {
    name: "India",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  IRL: {
    name: "Ireland",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  IRN: {
    name: "Iran",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  IRQ: {
    name: "Iraq",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ISL: {
    name: "Iceland",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ISR: {
    name: "Israel",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ITA: {
    name: "Italy",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  JAM: {
    name: "Jamaica",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  JOR: {
    name: "Jordan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  JPN: {
    name: "Japan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  KAZ: {
    name: "Kazakhstan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  KEN: {
    name: "Kenya",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  KGZ: {
    name: "Kyrgyzstan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  KHM: {
    name: "Cambodia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  KOR: {
    name: "South Korea",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  XXK: {
    name: "Kosovo",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  KWT: {
    name: "Kuwait",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LAO: {
    name: "Laos",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LBN: {
    name: "Lebanon",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LBR: {
    name: "Liberia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LBY: {
    name: "Libya",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LKA: {
    name: "Sri Lanka",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LSO: {
    name: "Lesotho",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LTU: {
    name: "Lithuania",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LUX: {
    name: "Luxembourg",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LVA: {
    name: "Latvia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MAR: {
    name: "Morocco",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MDA: {
    name: "Moldova",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MDG: {
    name: "Madagascar",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MEX: {
    name: "Mexico",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MKD: {
    name: "North Macedonia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MLI: {
    name: "Mali",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MMR: {
    name: "Myanmar",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MNE: {
    name: "Montenegro",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MNG: {
    name: "Mongolia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MOZ: {
    name: "Mozambique",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MRT: {
    name: "Mauritania",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MWI: {
    name: "Malawi",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MYS: {
    name: "Malaysia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NAM: {
    name: "Namibia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NCL: {
    name: "New Caledonia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NER: {
    name: "Niger",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NGA: {
    name: "Nigeria",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NIC: {
    name: "Nicaragua",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NLD: {
    name: "Netherlands",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NOR: {
    name: "Norway",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NPL: {
    name: "Nepal",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NZL: {
    name: "New Zealand",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  OMN: {
    name: "Oman",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PAK: {
    name: "Pakistan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PAN: {
    name: "Panama",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PER: {
    name: "Peru",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PHL: {
    name: "Philippines",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PNG: {
    name: "Papua New Guinea",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  POL: {
    name: "Poland",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PRI: {
    name: "Puerto Rico",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PRK: {
    name: "North Korea",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PRT: {
    name: "Portugal",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PRY: {
    name: "Paraguay",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  QAT: {
    name: "Qatar",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ROU: {
    name: "Romania",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  RUS: {
    name: "Russia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  RWA: {
    name: "Rwanda",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ESH: {
    name: "Western Sahara",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SAU: {
    name: "Saudi Arabia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SDN: {
    name: "Sudan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SSD: {
    name: "South Sudan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SEN: {
    name: "Senegal",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SLB: {
    name: "Solomon Islands",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SLE: {
    name: "Sierra Leone",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SLV: {
    name: "El Salvador",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SOM: {
    name: "Somalia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SRB: {
    name: "Serbia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SUR: {
    name: "Suriname",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SVK: {
    name: "Slovakia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SVN: {
    name: "Slovenia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SWE: {
    name: "Sweden",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SWZ: {
    name: "Eswatini",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SYR: {
    name: "Syria",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TCD: {
    name: "Chad",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TGO: {
    name: "Togo",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  THA: {
    name: "Thailand",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TJK: {
    name: "Tajikistan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TKM: {
    name: "Turkmenistan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TLS: {
    name: "Timor",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TTO: {
    name: "Trinidad and Tobago",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TUN: {
    name: "Tunisia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TUR: {
    name: "Turkey",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TWN: {
    name: "Taiwan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TZA: {
    name: "Tanzania",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  UGA: {
    name: "Uganda",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  UKR: {
    name: "Ukraine",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  URY: {
    name: "Uruguay",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  USA: {
    name: "United States",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  UZB: {
    name: "Uzbekistan",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  VEN: {
    name: "Venezuela",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  VNM: {
    name: "Vietnam",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  VUT: {
    name: "Vanuatu",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PSX: {
    name: "West Bank",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  YEM: {
    name: "Yemen",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ZAF: {
    name: "South Africa",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ZMB: {
    name: "Zambia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ZWE: {
    name: "Zimbabwe",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  CPV: {
    name: "Cape Verde",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  COM: {
    name: "Comoros",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MUS: {
    name: "Mauritius",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SYC: {
    name: "Seychelles",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BHR: {
    name: "Bahrain",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MDV: {
    name: "Maldives",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MHL: {
    name: "Marshall Islands",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  FSM: {
    name: "Micronesia (country)",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  NRU: {
    name: "Nauru",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  PLW: {
    name: "Palau",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  WSM: {
    name: "Samoa",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SGP: {
    name: "Singapore",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TON: {
    name: "Tonga",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  TUV: {
    name: "Tuvalu",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  ATG: {
    name: "Antigua and Barbuda",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  BRB: {
    name: "Barbados",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  DMA: {
    name: "Dominica",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  GRD: {
    name: "Grenada",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  KNA: {
    name: "Saint Kitts and Nevis",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LCA: {
    name: "Saint Lucia",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  VCT: {
    name: "Saint Vincent and the Grenadines",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  AND: {
    name: "Andorra",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  LIE: {
    name: "Liechtenstein",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MLT: {
    name: "Malta",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  MCO: {
    name: "Monaco",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  SMR: {
    name: "San Marino",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  KIR: {
    name: "Kiribati",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
  STP: {
    name: "Sao Tome and Principe",
    flag: "",
    paymentMethods: "",
    onramps: 0,
  },
};
