export const onramper = [
  {
    country: "Nigeria",
    currency: "NGN",
    local_payment_methods: [
      "Bank Transfer",
      "Credit Card",
      "Debit Card",
      "Instant Bank Transfer",
    ],
    supported_onramps: ["Neocrypto", "Onramp Money", "LocalRamp", "TransFi"],
  },
  {
    country: "Vietnam",
    currency: "VND",
    local_payment_methods: ["Momo", "Viettel Pay", "Zalo Pay", "Viet QR"],
    supported_onramps: ["TransFi"],
  },
  {
    country: "Brazil",
    currency: "BRL",
    local_payment_methods: ["Pix"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "United States",
    currency: "USD",
    local_payment_methods: [
      "ACH Transfer",
      "Credit Card",
      "Debit Card",
      "Apple Pay",
      "Google Pay",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "India",
    currency: "INR",
    local_payment_methods: [
      "Bank Transfer",
      "Credit Card",
      "Debit Card",
      "UPI",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "United Kingdom",
    currency: "GBP",
    local_payment_methods: [
      "Faster Payments",
      "Credit Card",
      "Debit Card",
      "Apple Pay",
      "Google Pay",
    ],
    supported_onramps: ["TransFi", "Onramper"],
  },
  {
    country: "Canada",
    currency: "CAD",
    local_payment_methods: [
      "Interac",
      "Credit Card",
      "Debit Card",
      "Apple Pay",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Australia",
    currency: "AUD",
    local_payment_methods: ["BPAY", "POLi", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Germany",
    currency: "EUR",
    local_payment_methods: [
      "SEPA Transfer",
      "Credit Card",
      "Debit Card",
      "SOFORT",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Japan",
    currency: "JPY",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["TransFi", "Onramper"],
  },
  {
    country: "South Africa",
    currency: "ZAR",
    local_payment_methods: ["EFT", "Credit Card", "Debit Card"],
    supported_onramps: ["Neocrypto", "Onramper"],
  },
  {
    country: "China",
    currency: "CNY",
    local_payment_methods: ["Alipay", "WeChat Pay", "UnionPay"],
    supported_onramps: ["TransFi"],
  },
  {
    country: "Russia",
    currency: "RUB",
    local_payment_methods: ["Qiwi", "Yandex Money", "Credit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Saudi Arabia",
    currency: "SAR",
    local_payment_methods: ["MADA", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Mexico",
    currency: "MXN",
    local_payment_methods: ["SPEI", "OXXO", "Credit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "France",
    currency: "EUR",
    local_payment_methods: [
      "SEPA Transfer",
      "Credit Card",
      "Debit Card",
      "Paylib",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Italy",
    currency: "EUR",
    local_payment_methods: ["SEPA Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "South Korea",
    currency: "KRW",
    local_payment_methods: ["KakaoPay", "Credit Card", "Debit Card"],
    supported_onramps: ["TransFi"],
  },
  {
    country: "Singapore",
    currency: "SGD",
    local_payment_methods: ["PayNow", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Argentina",
    currency: "ARS",
    local_payment_methods: ["PagoFacil", "RapiPago", "Credit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Sweden",
    currency: "SEK",
    local_payment_methods: ["Swish", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Norway",
    currency: "NOK",
    local_payment_methods: ["Vipps", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Denmark",
    currency: "DKK",
    local_payment_methods: ["MobilePay", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "New Zealand",
    currency: "NZD",
    local_payment_methods: ["POLi", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Turkey",
    currency: "TRY",
    local_payment_methods: ["Papara", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Afghanistan",
    currency: "AFN",
    local_payment_methods: ["Bank Transfer", "Mobile Money"],
    supported_onramps: ["Onramp Money"],
  },
  {
    country: "Angola",
    currency: "AOA",
    local_payment_methods: ["Bank Transfer", "Mobile Money"],
    supported_onramps: ["Onramp Money"],
  },
  {
    country: "Albania",
    currency: "ALL",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "United Arab Emirates",
    currency: "AED",
    local_payment_methods: [
      "Bank Transfer",
      "Credit Card",
      "Debit Card",
      "Apple Pay",
      "Google Pay",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Argentina",
    currency: "ARS",
    local_payment_methods: [
      "Bank Transfer",
      "Credit Card",
      "Debit Card",
      "Mercado Pago",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Armenia",
    currency: "AMD",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "French Southern Territories",
    currency: "EUR",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Australia",
    currency: "AUD",
    local_payment_methods: [
      "Bank Transfer",
      "Credit Card",
      "Debit Card",
      "PayPal",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Austria",
    currency: "EUR",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Azerbaijan",
    currency: "AZN",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Burundi",
    currency: "BIF",
    local_payment_methods: ["Bank Transfer", "Mobile Money"],
    supported_onramps: ["Onramp Money"],
  },
  {
    country: "Belgium",
    currency: "EUR",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Benin",
    currency: "NGN",
    local_payment_methods: ["Bank Transfer", "Mobile Money"],
    supported_onramps: ["Onramp Money"],
  },
  {
    country: "Burkina Faso",
    currency: "NGN",
    local_payment_methods: ["Bank Transfer", "Mobile Money"],
    supported_onramps: ["Onramp Money"],
  },
  {
    country: "Bangladesh",
    currency: "BDT",
    local_payment_methods: ["Bank Transfer", "Mobile Money"],
    supported_onramps: ["Onramp Money"],
  },
  {
    country: "Bulgaria",
    currency: "BGN",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Bahamas",
    currency: "BSD",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Bosnia and Herzegovina",
    currency: "BAM",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Belarus",
    currency: "BYN",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Belize",
    currency: "BZD",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Bolivia",
    currency: "BOB",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Brazil",
    currency: "BRL",
    local_payment_methods: ["Pix", "Boleto Banc\u00e1rio", "Mercado Pago"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Brunei",
    currency: "BND",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Bhutan",
    currency: "BTN",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Botswana",
    currency: "BWP",
    local_payment_methods: ["Bank Transfer", "Mobile Money"],
    supported_onramps: ["Onramp Money"],
  },
  {
    country: "Central African Republic",
    currency: "NGN",
    local_payment_methods: ["Bank Transfer", "Mobile Money"],
    supported_onramps: ["Onramp Money"],
  },
  {
    country: "Canada",
    currency: "CAD",
    local_payment_methods: [
      "Bank Transfer",
      "Credit Card",
      "Debit Card",
      "Interac",
    ],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Switzerland",
    currency: "CHF",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "Chile",
    currency: "CLP",
    local_payment_methods: ["Bank Transfer", "Credit Card", "Debit Card"],
    supported_onramps: ["Onramper"],
  },
  {
    country: "China",
    currency: "CNY",
    local_payment_methods: ["Alipay", "WeChat Pay", "Bank Transfer"],
    supported_onramps: ["Onramper"],
  },
];
